import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';
import {
  DEFAULT_CATEGORIES,
  BudgetPeriodSummary,
  RecurringItem,
  Transaction,
  UserSettings,
} from '../types/budget';
import { HermeticBackupPayload } from '../types/storage';
import { calculateBudgetPeriodSummary, validateRatios } from '../services/budgetEngine';
import {
  createBackupPayload,
  restoreFromBackup,
  validateAndSanitizeBackup,
} from '../services/exportImportService';
import {
  generateUniqueId,
  processRecurringTransactions,
} from '../services/recurrenceService';
import {
  clearAllStorage,
  DEFAULT_SETTINGS,
  hydrateAll,
  saveRecurring,
  saveSettings,
  saveTransactions,
} from '../services/storageService';

export interface BudgetContextType {
  transactions: Transaction[];
  recurring: RecurringItem[];
  settings: UserSettings;
  categories: string[];
  isHydrated: boolean;
  currentPeriodKey: string;
  summary: BudgetPeriodSummary;
  setPeriodKey: (periodKey: string) => void;
  addTransaction: (
    transaction: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>
  ) => Promise<Transaction>;
  updateTransaction: (transaction: Transaction) => Promise<void>;
  deleteTransaction: (id: string) => Promise<void>;
  addRecurringItem: (
    item: Omit<RecurringItem, 'id' | 'createdAt' | 'updatedAt'>
  ) => Promise<RecurringItem>;
  updateRecurringItem: (item: RecurringItem) => Promise<void>;
  deleteRecurringItem: (id: string) => Promise<void>;
  updateSettings: (newSettings: Partial<UserSettings>) => Promise<void>;
  addCategory: (categoryName: string) => Promise<void>;
  deleteCategory: (categoryName: string) => Promise<void>;
  exportData: () => HermeticBackupPayload;
  importData: (rawJson: string) => Promise<{ success: boolean; error?: string }>;
  processRecurring: () => Promise<void>;
  refreshCalculations: () => void;
  resetAllData: () => Promise<void>;
}

const BudgetContext = createContext<BudgetContextType | undefined>(undefined);

export function getCurrentPeriodKey(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  return `${year}-${month}`;
}

export const BudgetProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [recurring, setRecurring] = useState<RecurringItem[]>([]);
  const [settings, setSettings] = useState<UserSettings>(DEFAULT_SETTINGS);
  const [isHydrated, setIsHydrated] = useState<boolean>(false);
  const [currentPeriodKey, setCurrentPeriodKey] = useState<string>(getCurrentPeriodKey());
  const [, setTick] = useState<number>(0);

  // 1. Storage Hydration on startup
  useEffect(() => {
    let isMounted = true;

    async function initialize() {
      try {
        const hydrated = await hydrateAll();
        if (!isMounted) return;

        let activeTransactions = hydrated.transactions;
        const activeRecurring = hydrated.recurring;
        const activeSettings = hydrated.settings;

        // Auto-evaluate recurring transactions for current month on startup
        const periodKey = getCurrentPeriodKey();
        const autoGenerated = processRecurringTransactions(
          activeRecurring,
          activeTransactions,
          periodKey
        );

        if (autoGenerated.length > 0) {
          activeTransactions = [...autoGenerated, ...activeTransactions];
          // Asynchronously persist updated ledger
          saveTransactions(activeTransactions).catch((err) =>
            console.error('Failed to persist auto-generated recurring transactions:', err)
          );
        }

        setTransactions(activeTransactions);
        setRecurring(activeRecurring);
        setSettings(activeSettings);
        setIsHydrated(true);
      } catch (err) {
        console.error('Failed during BudgetProvider initialization:', err);
        if (isMounted) {
          setIsHydrated(true);
        }
      }
    }

    initialize();

    return () => {
      isMounted = false;
    };
  }, []);

  // 2. Real-time synchronous calculation of budget summary (0ms latency)
  const summary = useMemo(() => {
    return calculateBudgetPeriodSummary(transactions, settings.ratios, currentPeriodKey);
  }, [transactions, settings.ratios, currentPeriodKey]);

  // 3. Transactions Mutations
  const addTransaction = useCallback(
    async (txInput: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transaction> => {
      const nowIso = new Date().toISOString();
      const newTx: Transaction = {
        ...txInput,
        id: generateUniqueId('tx'),
        createdAt: nowIso,
        updatedAt: nowIso,
      };

      // Synchronous in-memory update for 0ms UI response
      setTransactions((prev) => {
        let updatedPrev = [...prev];
        if (newTx.type === 'refund' && newTx.targetExpenseIds && newTx.targetExpenseIds.length > 0) {
          const targetIds = new Set(newTx.targetExpenseIds);
          let remainingRefund = newTx.amount;
          updatedPrev = updatedPrev.map((t) => {
            if (targetIds.has(t.id) && remainingRefund > 0) {
              const currentRefunded = t.refundedAmount || 0;
              const unrefunded = Math.max(0, t.amount - currentRefunded);
              const toApply = Math.min(unrefunded, remainingRefund);
              remainingRefund -= toApply;
              return {
                ...t,
                refundedAmount: Number((currentRefunded + toApply).toFixed(2)),
              };
            }
            return t;
          });
        }
        const next = [newTx, ...updatedPrev];
        // Asynchronous write-behind persistence
        saveTransactions(next).catch((err) =>
          console.error('Failed to persist transaction to AsyncStorage:', err)
        );
        return next;
      });

      return newTx;
    },
    []
  );

  const updateTransaction = useCallback(async (updatedTx: Transaction): Promise<void> => {
    const nowIso = new Date().toISOString();
    const finalTx: Transaction = {
      ...updatedTx,
      updatedAt: nowIso,
    };

    setTransactions((prev) => {
      const next = prev.map((t) => (t.id === finalTx.id ? finalTx : t));
      saveTransactions(next).catch((err) =>
        console.error('Failed to update transaction in AsyncStorage:', err)
      );
      return next;
    });
  }, []);

  const deleteTransaction = useCallback(async (id: string): Promise<void> => {
    setTransactions((prev) => {
      const deletedTx = prev.find((t) => t.id === id);
      let next = prev.filter((t) => t.id !== id);
      if (
        deletedTx &&
        deletedTx.type === 'refund' &&
        deletedTx.targetExpenseIds &&
        deletedTx.targetExpenseIds.length > 0
      ) {
        const targetIds = new Set(deletedTx.targetExpenseIds);
        let refundToRemove = deletedTx.amount;
        next = next.map((t) => {
          if (targetIds.has(t.id) && refundToRemove > 0) {
            const currentRefunded = t.refundedAmount || 0;
            const toRemove = Math.min(currentRefunded, refundToRemove);
            refundToRemove -= toRemove;
            return {
              ...t,
              refundedAmount: Number(Math.max(0, currentRefunded - toRemove).toFixed(2)),
            };
          }
          return t;
        });
      }
      saveTransactions(next).catch((err) =>
        console.error('Failed to delete transaction from AsyncStorage:', err)
      );
      return next;
    });
  }, []);

  // 4. Recurring Items Mutations
  const addRecurringItem = useCallback(
    async (
      itemInput: Omit<RecurringItem, 'id' | 'createdAt' | 'updatedAt'>
    ): Promise<RecurringItem> => {
      const nowIso = new Date().toISOString();
      const newItem: RecurringItem = {
        ...itemInput,
        id: generateUniqueId('rec'),
        createdAt: nowIso,
        updatedAt: nowIso,
      };

      setRecurring((prev) => {
        const next = [...prev, newItem];
        saveRecurring(next).catch((err) =>
          console.error('Failed to persist recurring item to AsyncStorage:', err)
        );
        return next;
      });

      return newItem;
    },
    []
  );

  const updateRecurringItem = useCallback(async (updatedItem: RecurringItem): Promise<void> => {
    const nowIso = new Date().toISOString();
    const finalItem: RecurringItem = {
      ...updatedItem,
      updatedAt: nowIso,
    };

    setRecurring((prev) => {
      const next = prev.map((r) => (r.id === finalItem.id ? finalItem : r));
      saveRecurring(next).catch((err) =>
        console.error('Failed to update recurring item in AsyncStorage:', err)
      );
      return next;
    });
  }, []);

  const deleteRecurringItem = useCallback(async (id: string): Promise<void> => {
    setRecurring((prev) => {
      const next = prev.filter((r) => r.id !== id);
      saveRecurring(next).catch((err) =>
        console.error('Failed to delete recurring item from AsyncStorage:', err)
      );
      return next;
    });
  }, []);

  // 5. Settings Mutation
  const updateSettings = useCallback(
    async (partialSettings: Partial<UserSettings>): Promise<void> => {
      // Validate ratios if present
      if (partialSettings.ratios) {
        const validation = validateRatios(partialSettings.ratios);
        if (!validation.isValid) {
          throw new Error(validation.error || 'Invalid budget ratios');
        }
      }

      setSettings((prev) => {
        const next: UserSettings = {
          ...prev,
          ...partialSettings,
          ratios: partialSettings.ratios ? { ...partialSettings.ratios } : prev.ratios,
        };
        saveSettings(next).catch((err) =>
          console.error('Failed to persist settings to AsyncStorage:', err)
        );
        return next;
      });
    },
    []
  );

  const categories = useMemo(() => {
    const custom = settings?.customCategories || [];
    const all = [...DEFAULT_CATEGORIES, ...custom];
    // Deduplicate preserving order
    return Array.from(new Set(all));
  }, [settings?.customCategories]);

  const addCategory = useCallback(async (categoryName: string): Promise<void> => {
    const trimmed = categoryName.trim();
    if (!trimmed) return;
    const current = settings?.customCategories || [];
    if (categories.includes(trimmed)) return;

    const nextCustom = [...current, trimmed];
    await updateSettings({ customCategories: nextCustom });
  }, [categories, settings?.customCategories, updateSettings]);

  const deleteCategory = useCallback(async (categoryName: string): Promise<void> => {
    const current = settings?.customCategories || [];
    const nextCustom = current.filter((c) => c !== categoryName);
    await updateSettings({ customCategories: nextCustom });
  }, [settings?.customCategories, updateSettings]);

  // 6. Manual Recurring Synthesis
  const processRecurring = useCallback(async (): Promise<void> => {
    setTransactions((prevTx) => {
      const generated = processRecurringTransactions(recurring, prevTx, currentPeriodKey);
      if (generated.length === 0) return prevTx;

      const next = [...generated, ...prevTx];
      saveTransactions(next).catch((err) =>
        console.error('Failed to save recurring transactions:', err)
      );
      return next;
    });
  }, [recurring, currentPeriodKey]);

  // 7. Backup Export & Import
  const exportData = useCallback((): HermeticBackupPayload => {
    return createBackupPayload(transactions, recurring, settings);
  }, [transactions, recurring, settings]);

  const importData = useCallback(
    async (rawJson: string): Promise<{ success: boolean; error?: string }> => {
      const validation = validateAndSanitizeBackup(rawJson);
      if (!validation.isValid || !validation.payload) {
        return { success: false, error: validation.error || 'Validation failed' };
      }

      try {
        await restoreFromBackup(validation.payload);
        setTransactions(validation.payload.data.transactions);
        setRecurring(validation.payload.data.recurring);
        setSettings(validation.payload.data.settings);
        return { success: true };
      } catch (err: any) {
        console.error('Failed to restore database from backup payload:', err);
        return { success: false, error: err?.message || 'Restore failed' };
      }
    },
    []
  );

  const refreshCalculations = useCallback(() => {
    setTick((t) => t + 1);
  }, []);

  const resetAllData = useCallback(async (): Promise<void> => {
    await clearAllStorage();
    setTransactions([]);
    setRecurring([]);
    setSettings(DEFAULT_SETTINGS);
  }, []);

  const value: BudgetContextType = {
    transactions,
    recurring,
    settings,
    categories,
    isHydrated,
    currentPeriodKey,
    summary,
    setPeriodKey: setCurrentPeriodKey,
    addTransaction,
    updateTransaction,
    deleteTransaction,
    addRecurringItem,
    updateRecurringItem,
    deleteRecurringItem,
    updateSettings,
    addCategory,
    deleteCategory,
    exportData,
    importData,
    processRecurring,
    refreshCalculations,
    resetAllData,
  };

  return <BudgetContext.Provider value={value}>{children}</BudgetContext.Provider>;
};

export function useBudget(): BudgetContextType {
  const context = useContext(BudgetContext);
  if (!context) {
    throw new Error('useBudget must be used within a BudgetProvider');
  }
  return context;
}

export { BudgetContext };
